" my preferences
set tabstop=4
set shiftwidth=4
set expandtab
set autoindent 
set background=dark
syntax on

" :W to save with sudo if forgot to open with it
command W :execute ':silent w !sudo tee % > /dev/null' | :edit!

" Remember position when reopening files
if has("autocmd")
  " When editing a file, always jump to the last cursor position
  autocmd BufReadPost * if line("'\"") > 0 && line ("'\"") <= line("$") | exe "normal! g`\"" | endif
endif

" yank between different instances of vim
set viminfo='100,<1000,s100,h,n~/.vim/viminfo

augroup sync_clipboard
  autocmd!
  autocmd TextYankPost * silent! wviminfo
  "autocmd CursorMoved * silent! rviminfo
  " Load before EVERY paste
  nnoremap p :rviminfo<CR>p
  nnoremap P :rviminfo<CR>P
  vnoremap p :rviminfo<CR>p
  vnoremap P :rviminfo<CR>P
augroup END

" auto install vim-plug
let data_dir = has('nvim') ? stdpath('data') . '/site' : '~/.vim'
if empty(glob(data_dir . '/autoload/plug.vim'))
  silent execute '!curl -fLo '.data_dir.'/autoload/plug.vim --create-dirs  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin('~/.vim/plugged')

Plug 'jiangmiao/auto-pairs' 

call plug#end()
