set tabstop=4
set shiftwidth=4
set expandtab
set autoindent 
set background=dark
syntax on

" Automatically append closing characters
inoremap ( ()<Left>
inoremap [ []<Left>
inoremap { {}<Left>
inoremap " ""<Left>
inoremap ' ''<Left>

